# Generated by Django 2.2.2 on 2020-05-05 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(db_index=True, max_length=150)),
                ('phone_number', models.IntegerField(unique=True)),
                ('email', models.EmailField(default='musa@musa.ru', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id_transaction', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('t_trans', models.IntegerField(choices=[(1, 'Перевод физ. лицу'), (2, 'Перевод перевод юр. лицу')])),
                ('t_client', models.IntegerField(choices=[(1, 'Брокер'), (2, 'Кредитная карта'), (3, 'Дебетовая карта'), (4, 'Юридическое лицо'), (5, 'Сберегательный счет')])),
                ('amount', models.IntegerField(db_index=True)),
                ('currency', models.CharField(max_length=3)),
                ('payer_bank_name', models.CharField(max_length=100)),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banks.Client')),
            ],
        ),
    ]
