# Generated by Django 2.2.2 on 2020-05-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id_client',
            field=models.IntegerField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
