# Generated by Django 2.2.2 on 2020-05-05 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_client_id_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='id_client',
        ),
    ]
