# Generated by Django 2.2.2 on 2020-05-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_auto_20200507_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='alert',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='payee',
            field=models.CharField(default='Андрей', max_length=150, verbose_name='Получатель'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(db_index=True, verbose_name='Сумма перевода'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата проведения транзакции'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer_bank_name',
            field=models.CharField(max_length=150, verbose_name='Банк получателя'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='t_trans',
            field=models.IntegerField(choices=[(1, 'Перевод физ. лицу'), (2, 'Перевод перевод юр. лицу')], verbose_name='Тип транзакции'),
        ),
    ]
