# Generated by Django 2.2.2 on 2020-05-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_auto_20200509_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payee_bank_name',
            field=models.CharField(default='VTB', max_length=150, verbose_name='Банк получателя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer_bank_name',
            field=models.CharField(max_length=100, verbose_name='Банк плательщика'),
        ),
    ]
