# Generated by Django 2.2.2 on 2020-05-10 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_auto_20200510_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='date_pub',
        ),
    ]
