# Generated by Django 2.2.2 on 2020-05-10 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_remove_transaction_date_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата проведения транзакции'),
            preserve_default=False,
        ),
    ]
