# Generated by Django 2.2.2 on 2020-05-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200506_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='amountrur',
        ),
        migrations.AddField(
            model_name='rules',
            name='amountrur_gr',
            field=models.IntegerField(default=100, verbose_name='Верхний предел суммы в рублях'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rules',
            name='amountrur_le',
            field=models.IntegerField(default=90, verbose_name='Нижний предел суммы в рублях'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rules',
            name='date_count',
            field=models.IntegerField(default=1, verbose_name='Количество дней'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rules',
            name='eur',
            field=models.BooleanField(verbose_name='Евро'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='rur',
            field=models.BooleanField(verbose_name='Рубли'),
        ),
        migrations.AlterField(
            model_name='rules',
            name='usd',
            field=models.BooleanField(verbose_name='Доллар'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='user.Rules', verbose_name='Группа'),
        ),
    ]
