# Generated by Django 2.2.2 on 2020-05-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200508_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='group',
            field=models.ManyToManyField(related_name='group', to='user.Rules', verbose_name='Группа'),
        ),
    ]
