# Generated by Django 2.2.2 on 2020-05-09 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0013_auto_20200508_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_client', models.IntegerField(blank=True, choices=[(1, 'Брокер'), (2, 'Кредитная карта'), (3, 'Дебетовая карта'), (4, 'Юридическое лицо'), (5, 'Сберегательный счет')], default=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
