# Generated by Django 2.2.2 on 2020-05-09 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_auto_20200509_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_client',
            field=models.ManyToManyField(null=True, to='user.Rules'),
        ),
    ]
