# Generated by Django 2.2.2 on 2020-05-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_auto_20200509_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type_client',
            field=models.ManyToManyField(default=1, to='user.Rules'),
        ),
    ]
